reporting: "off"
startuppopupversion: 1
gui:
  theme:
    lightTheme: true
customCommands:
  - key: "C"
    command: "npx git-cz"
    context: "files"
    loadingText: "opening commitizen commit tool"
    subprocess: true

